train: path2/train/images
val: path2/valid/images
test: path2/test/images

nc: 2
names: ['Basketball Hoop', 'Basketball']

roboflow:
  workspace: 034-ganesh-kumar-m-v-cs-r2lwe
  project: basketball-lhqoe
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/034-ganesh-kumar-m-v-cs-r2lwe/basketball-lhqoe/dataset/1