train: YOLOTrain2/train/images
val: YOLOTrain2/valid/images
test: YOLOTrain2/test/images

# replace '...' with your local absolute paths
# download the dataset used here: https://universe.roboflow.com/034-ganesh-kumar-m-v-cs-r2lwe/basketball-lhqoe/dataset/1

nc: 2
names: ['Ball', 'Hoop']
