train: YOLOBallOnly1/train/images
val: YOLOBallOnly1/valid/images
test: YOLOBallOnly1/test/images

# replace '...' with your local absolute paths
# download the dataset used here: https://universe.roboflow.com/034-ganesh-kumar-m-v-cs-r2lwe/basketball-lhqoe/dataset/1

nc: 2
names: ['basketball', 'sports ball']
